### ISSUE TITLE
Shoot a video

### ISSUE THREAD

**Issue by feross** [feross/oculus-drone#1]
The other oculus drone project: http://www.polygon.com/2013/7/25/4555832/watch-a-drone-being-controlled-by-the-oculus-rift

We should go to a park and shoot a similar video, but with actual _control_ from the Oculus Rift, and with the code released open source so others can do the same & improve it. Will get much internet love, guaranteed.

**Comment by sysr-q** [comment]
"Internet love, guaranteed" - @feross on the topic of all of his projects.
It would blow theirs out of the water - no laptop attached to an overpowered drone and all.

**Comment by feross** [comment]
This never happened. Closing this issue.
